### ISSUE TITLE
Heroku へのデプロイ

### ISSUE THREAD

**Issue by knokmki612** [webdino/lyceum-pokemon#93]
@knokmki612 ができたら完了

参考 https://nitro.unjs.io/deploy/providers/heroku

**Comment by knokmki612** [comment]
heroku cli をインストールしていなかったのでそこからはじめる

[toolbox](https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/) でコンテナー環境を作成して入る

```
toolbox create heroku
toolbox enter heroku
```

`dnf search heroku` などとしたが fedora のパッケージリポジトリは配布されていなかった

https://devcenter.heroku.com/ja/articles/heroku-cli#standalone-installation-with-a-tarball より

`curl https://cli-assets.heroku.com/install.sh | sh` でインストール

以下のコマンドにより heroku cli が利用可能な状態であることを確認

```shell
$ heroku --version
heroku/7.62.0 linux-x64 node-v14.19.0
```

**Comment by kou029w** [comment]
公式ドキュメントには無いですが npx heroku でもおそらく OK と思います。

**Comment by knokmki612** [comment]
以下を実行

```
heroku create <アプリ名>
heroku buildpacks:set heroku/nodejs --app <アプリ名>
heroku config:set NITRO_PRESET=heroku --app <アプリ名>
heroku git:remote --app <アプリ名>
```

またブラウザで `https://dashboard.heroku.com/apps/<アプリ名>/settings` にアクセスし、環境変数

- AWS_ACCESS_KEY
- AWS_SECRET_ACCESS_KEY
- BUCKET_NAME
- VITE_SERVER_ORIGIN

を設定

**Comment by knokmki612** [comment]
`git push heroku main` したところビルドに失敗

<details>
<summary>ログ</summary>

```
$ git push heroku main
Enumerating objects: 657, done.
Counting objects: 100% (657/657), done.
Delta compression using up to 6 threads
Compressing objects: 100% (573/573), done.
Writing objects: 100% (657/657), 581.33 KiB | 7.09 MiB/s, done.
Total 657 (delta 308), reused 148 (delta 69), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: heroku/nodejs
remote: -----> Node.js app detected
remote:        
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version 16.x...
remote:        Downloading and installing node 16.17.0...
remote:        Using default npm version: 8.15.0
remote:        
remote: -----> Installing dependencies
remote:        Installing node modules
remote:        
remote:        added 1240 packages, and audited 1241 packages in 15s
remote:        
remote:        192 packages are looking for funding
remote:          run `npm fund` for details
remote:        
remote:        found 0 vulnerabilities
remote:        
remote: -----> Build
remote:        Running build
remote:        
remote:        > build
remote:        > nuxi build
remote:        
remote:        Nuxt CLI v3.0.0-27414150.3589a2d
remote: 
remote:  ERROR  Cannot resolve preset: heroku
remote: 
remote:   at getNitroContext (node_modules/@nuxt/nitro/dist/index.mjs:1661:11)
remote:   at initNitro (node_modules/nuxt3/dist/chunks/nitro-legacy.mjs:22:24)
remote:   at initNuxt (node_modules/nuxt3/dist/chunks/index.mjs:1098:9)
remote:   at async loadNuxt (node_modules/nuxt3/dist/chunks/index.mjs:1148:5)
remote:   at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:611:19)
remote:   at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:26:18)
remote:   at async _main (node_modules/nuxi/dist/chunks/index.mjs:384:7)
remote: 
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        Some possible problems:
remote:        
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to kuno-tuqulore-lyceum-pokemon.
remote:
```

</details>

**Comment by knokmki612** [comment]
> remote:  ERROR  Cannot resolve preset: heroku

nitro のバージョンが古いからかherokuプリセットが存在しないように思った

NITRO_PRESETを取り除き再度 `git push heroku main` したところビルドをパス

<details>
<summary>ログ</summary>

```
$ git push heroku main
Enumerating objects: 657, done.
Counting objects: 100% (657/657), done.
Delta compression using up to 6 threads
Compressing objects: 100% (573/573), done.
Writing objects: 100% (657/657), 582.22 KiB | 7.19 MiB/s, done.
Total 657 (delta 308), reused 148 (delta 69), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: heroku/nodejs
remote: -----> Node.js app detected
remote:        
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version 16.x...
remote:        Downloading and installing node 16.17.0...
remote:        Using default npm version: 8.15.0
remote:        
remote: -----> Installing dependencies
remote:        Installing node modules
remote:        
remote:        added 1240 packages, and audited 1241 packages in 17s
remote:        
remote:        192 packages are looking for funding
remote:          run `npm fund` for details
remote:        
remote:        found 0 vulnerabilities
remote:        
remote: -----> Build
remote:        Running build
remote:        
remote:        > build
remote:        > nuxi build
remote:        
remote:        Nuxt CLI v3.0.0-27414150.3589a2d
remote:        ℹ Vite warmed up in 1078ms
remote:        ℹ Client built in 3883ms
remote:        ℹ Building server...
remote:        ✔ Server built in 1614ms
remote:        ℹ Nitro preset is server
remote:        ℹ Cleaning up .output
remote:        start Generating public...
remote:        ✔ Generated public .output/public
remote:        start Building server...
remote:        start Writing server bundle...
remote:        ✔ Server built
remote:          ├─ .output/server/index.mjs (285 B) (178 B gzip)
remote:          ├─ .output/server/chunks/nitro/static.mjs (7.96 kB) (2.34 kB gzip)
remote:          ├─ .output/server/chunks/nitro/server.mjs (71.5 kB) (24.4 kB gzip)
remote:          ├─ .output/server/chunks/middleware/index.mjs (5.17 kB) (1.39 kB gzip)
remote:          ├─ .output/server/chunks/index.mjs (396 kB) (91.3 kB gzip)
remote:          ├─ .output/server/chunks/app/vue3.mjs (284 B) (200 B gzip)
remote:          ├─ .output/server/chunks/app/server.mjs (210 kB) (41.1 kB gzip)
remote:          ├─ .output/server/chunks/app/render.mjs (23 kB) (6.33 kB gzip)
remote:          └─ .output/server/chunks/app/client.manifest.mjs (5.26 kB) (762 B gzip)
remote:        Σ Total size: 4.27 MB (1.15 MB gzip)
remote:        ℹ You can preview this build using nuxi preview
remote:        
remote: -----> Caching build
remote:        - npm cache
remote:        
remote: -----> Pruning devDependencies
remote:        
remote:        up to date, audited 1 package in 4s
remote:        
remote:        found 0 vulnerabilities
remote:        
remote: -----> Build succeeded!
remote: -----> Discovering process types
remote:        Procfile declares types     -> (none)
remote:        Default types for buildpack -> web
remote: 
remote: -----> Compressing...
remote:        Done: 33.9M
remote: -----> Launching...
remote:        Released v9
```

</details>

**Comment by kou029w** [comment]
(参考) 環境変数の設定 https://devcenter.heroku.com/ja/articles/config-vars#set-a-config-var

**Comment by knokmki612** [comment]
デプロイ先の url にアクセスしたところ Application error という画面が表示された

`heroku logs --tail` するよう促されたので `heroku logs --tail --app <アプリ名>` したところ以下のログを得られた

<details>
<summary>ログ</summary>

```
022-08-18T02:14:28.088811+00:00 app[web.1]: 
2022-08-18T02:14:28.088827+00:00 app[web.1]: > start
2022-08-18T02:14:28.088828+00:00 app[web.1]: > node .output/server/index.mjs
2022-08-18T02:14:28.088828+00:00 app[web.1]: 
2022-08-18T02:14:28.245981+00:00 app[web.1]: Listening on http://localhost:52804/
2022-08-18T02:15:26.386905+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2022-08-18T02:15:26.452633+00:00 heroku[web.1]: Stopping process with SIGKILL
2022-08-18T02:15:26.474001+00:00 app[web.1]: Error waiting for process to terminate: No child processes
2022-08-18T02:15:26.590707+00:00 heroku[web.1]: Process exited with status 22
2022-08-18T02:15:26.659593+00:00 heroku[web.1]: State changed from starting to crashed
2022-08-18T02:15:26.663518+00:00 heroku[web.1]: State changed from crashed to starting
2022-08-18T02:15:28.324112+00:00 heroku[web.1]: Starting process with command `npm start`
2022-08-18T02:15:29.971745+00:00 app[web.1]: 
2022-08-18T02:15:29.971753+00:00 app[web.1]: > start
2022-08-18T02:15:29.971753+00:00 app[web.1]: > node .output/server/index.mjs
2022-08-18T02:15:29.971753+00:00 app[web.1]: 
2022-08-18T02:15:30.101181+00:00 app[web.1]: Listening on http://localhost:12730/
2022-08-18T02:16:28.558995+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2022-08-18T02:16:28.661358+00:00 heroku[web.1]: Stopping process with SIGKILL
2022-08-18T02:16:28.676972+00:00 app[web.1]: Error waiting for process to terminate: No child processes
2022-08-18T02:16:28.789431+00:00 heroku[web.1]: Process exited with status 22
2022-08-18T02:16:29.116633+00:00 heroku[web.1]: State changed from starting to crashed
```

</details>

**Comment by knokmki612** [comment]
`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch` で検索したところホストに `0.0.0.0` を指定することで解消するという記事を発見

参考: https://zenn.dev/platina/articles/49b9a930416f1c

`heroku config:set NUXT_HOST=0.0.0.0 --app <アプリ名>` してしばらくしたところブラウザでアクセス可能になったことを確認

**Comment by dynamis** [comment]
手順を整理した。後で README にも書き足しておきます:

```
// zip 展開して新規 git リポジトリにする場合
git init
git branch -m main
git add .
git commit -m "initial commit"

// git clone から始める場合はここから
// heroku login
// APP_NAME=<your_heroku_app_name>
// BUCKET_NAME=<your_aws_s3_bucket_name>
heroku create $APP_NAME
heroku git:remote --app $APP_NAME
heroku config:set AWS_ACCESS_KEY_ID=**** --app $APP_NAME
heroku config:set AWS_SECRET_ACCESS_KEY=******** --app $APP_NAME
heroku config:set BUCKET_NAME=$BUCKET_NAME --app $APP_NAME
heroku config:set REGION=ap-northeast-1 --app $APP_NAME
heroku config:set VITE_SERVER_ORIGIN=https://$APP_NAME.herokuapp.com --app $APP_NAME
heroku config:set NUXT_HOST=0.0.0.0 --app $APP_NAME
git push heroku main
```
